const uuidv1 = require('uuid').v1;
const faker = require('faker');
module.exports = [
  {
    uuid: uuidv1(),
    label: 'smoke1',
    data: {},
    group: '_default',
    url: '/predefined/media/video/backgrounds/smoke1.webm',
    extension: 'webm',
    mime: 'video/webm',
    size: 0,
    content_type: 'video',
    local_path: '/predefined/media/video/backgrounds',
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent()
  },
  {
    uuid: uuidv1(),
    label: 'abstract1',
    data: {},
    group: '_default',
    url: '/predefined/media/video/backgrounds/abstract1.webm',
    extension: 'webm',
    mime: 'video/webm',
    size: 0,
    content_type: 'video',
    local_path: '/predefined/media/video/backgrounds',
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent()
  },
  {
    uuid: uuidv1(),
    label: 'abstract2',
    data: {},
    group: '_default',
    url: '/predefined/media/video/backgrounds/abstract2.webm',
    extension: 'webm',
    mime: 'video/webm',
    size: 0,
    content_type: 'video',
    local_path: '/predefined/media/video/backgrounds',
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent()
  },
  {
    uuid: uuidv1(),
    label: 'football1',
    data: {},
    group: '_default',
    url: '/predefined/media/video/backgrounds/football1.webm',
    extension: 'webm',
    mime: 'video/webm',
    size: 0,
    content_type: 'video',
    local_path: '/predefined/media/video/backgrounds',
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent()
  },
  {
    uuid: uuidv1(),
    label: 'football2',
    data: {},
    group: '_default',
    url: '/predefined/media/video/backgrounds/football2.webm',
    extension: 'webm',
    mime: 'video/webm',
    size: 0,
    content_type: 'video',
    local_path: '/predefined/media/video/backgrounds',
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent()
  },
  {
    uuid: uuidv1(),
    label: 'football3',
    data: {},
    group: '_default',
    url: '/predefined/media/video/backgrounds/football3.webm',
    extension: 'webm',
    mime: 'video/webm',
    size: 0,
    content_type: 'video',
    local_path: '/predefined/media/video/backgrounds',
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent()
  },
  {
    uuid: uuidv1(),
    label: 'hockey1',
    data: {},
    group: '_default',
    url: '/predefined/media/video/backgrounds/hockey1.webm',
    extension: 'webm',
    mime: 'video/webm',
    size: 0,
    content_type: 'video',
    local_path: '/predefined/media/video/backgrounds',
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent()
  },
  {
    uuid: uuidv1(),
    label: 'smoke1',
    data: {},
    group: '_default',
    url: '/predefined/media/video/backgrounds/smoke1.webm',
    extension: 'webm',
    mime: 'video/webm',
    size: 0,
    content_type: 'video',
    local_path: '/predefined/media/video/backgrounds',
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent()
  }
];
