const fcbLineupPlayers = [
  // {
  //   label: 'Aznou',
  //   position: 'Defender',
  //   value: 'Aznou',
  //   id: 'b0l4lfplx1we1xo5usm0h2ec4',
  //   shirtNumber: '49',
  //   shortFirstName: 'Adam',
  //   shortLastName: 'Aznou',
  //   posLen: 1,
  //   currentPos: 1,
  //   // TODO:
  //   // update gray and black Len and Pos when we get player images for these jerseys
  //   grayLen: 1,
  //   grayPos: 1,
  //   blackLen: 1,
  //   blackPos: 1,
  // },
  {
    label: 'Boey',
    position: 'Defender',
    value: 'Boey',
    id: '70esd7csbds20h5uazwktcbje',
    shirtNumber: '23',
    shortFirstName: 'Sacha',
    shortLastName: 'Boey',
    arabicName: 'بوي',
    posLen: 2,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 2,
    blackPos: 1,
  },
  {
    label: 'Nicolas',
    position: 'Forward',
    value: 'Nicolas',
    id: 'amcwh6w0brmkttg4uc5qm6z9w',
    shirtNumber: '11',
    shortFirstName: 'Nicolas',
    shortLastName: 'Jackson',
    arabicName: 'جاكسون',
    posLen: 2,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 2,
    blackPos: 1,
  },
  {
    label: 'Davies',
    position: 'Defender',
    value: 'Davies',
    id: '582uvj0i3dvm0zwbou9q68pgp',
    shirtNumber: '19',
    shortFirstName: 'Alphonso',
    shortLastName: 'Davies',
    arabicName: 'ديفيز',
    posLen: 3,
    currentPos: 1,
    grayLen: 2,
    grayPos: 1,
    blackLen: 4,
    blackPos: 1,
  },
  {
    firstName: "Luis Fernando",
    formationPlace: "11",
    lastName: "Díaz Marulanda",
    matchName: "L. Díaz",
    id: "5ch0r2awkzjfd4hv6kbw6c9gp",
    position: "Attacking Midfielder",
    positionSide: "Left",
    shirtNumber: 14,
    shortFirstName: "Luis",
    shortLastName: "Luis Díaz",
    arabicName: 'لويس دياز',
    label: 'Díaz',
    posLen: 3,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 4,
    blackPos: 1,
  },
  // {
  //   label: 'Dier',
  //   position: 'Defender',
  //   value: 'Dier',
  //   id: 'az7wa6km1zhvsb8y4mndlogyd',
  //   shirtNumber: '15',
  //   shortFirstName: 'Eric',
  //   shortLastName: 'Dier',
  //   posLen: 2,
  //   currentPos: 1,
  // },
  {
    label: 'Gnabry',
    position: 'Forward',
    value: 'Gnabry',
    id: '4ysxvym6ww4f9d3hflkqsbf11',
    shirtNumber: '7',
    shortFirstName: 'Serge',
    shortLastName: 'Gnabry',
    arabicName: 'جنابري',
    posLen: 2,
    currentPos: 1,
    grayLen: 2,
    grayPos: 1,
    blackLen: 3,
    blackPos: 1,
  },
  {
    label: 'Goretzka',
    position: 'Midfielder',
    value: 'Goretzka',
    id: '4w4ldzomkj7fhrc51iimz8no5',
    shirtNumber: '8',
    shortFirstName: 'Leon',
    shortLastName: 'Goretzka',
    arabicName: 'جوريتزكا',
    posLen: 2,
    currentPos: 1,
    grayLen: 2,
    grayPos: 1,
    blackLen: 3,
    blackPos: 1,
  },
  {
    label: 'Guerreiro',
    position: 'Defender',
    value: 'Guerreiro',
    id: '6ie5meimavc8kwohr6lrdyket',
    shirtNumber: '22',
    shortFirstName: 'Raphaël',
    shortLastName: 'Guerreiro',
    arabicName: 'جيريرو',
    posLen: 1,
    currentPos: 1,
    grayLen: 2,
    grayPos: 1,
    blackLen: 2,
    blackPos: 1,
  },
  {
    label: 'Kane',
    position: 'Forward',
    value: 'Kane',
    id: 'b9g4qurpll4wizajo95c406hh',
    shirtNumber: '9',
    shortFirstName: 'Harry',
    shortLastName: 'Kane',
    arabicName: 'كين',
    posLen: 3,
    currentPos: 1,
    grayLen: 3,
    grayPos: 1,
    blackLen: 4,
    blackPos: 1,
  },
  {
    label: 'Kim',
    position: 'Defender',
    value: 'Kim',
    id: '2p1pns6j6id4nx3nbi7fv0wrt',
    shirtNumber: '3',
    shortFirstName: 'Min-Jae',
    shortLastName: 'MinJae',
    arabicName: 'مين-جاي',
    posLen: 3,
    currentPos: 1,
    grayLen: 2,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
  },
  {
    label: 'Kimmich',
    position: 'Midfielder',
    value: 'Kimmich',
    id: '97nv3y9z2ajz6b4ynoo0jn3kl',
    shirtNumber: '6',
    shortFirstName: 'Joshua',
    shortLastName: 'Kimmich',
    arabicName: 'كيميش',
    posLen: 3,
    currentPos: 1,
    grayLen: 3,
    grayPos: 1,
    blackLen: 3,
    blackPos: 1,
  },
  {
    label: 'Laimer',
    position: 'Midfielder',
    value: 'Laimer',
    id: '1qthvf5krys0pzk24h8wtr9at',
    shirtNumber: '27',
    shortFirstName: 'Konrad',
    shortLastName: 'Laimer',
    arabicName: 'لايمر',
    posLen: 2,
    currentPos: 1,
    grayLen: 2,
    grayPos: 1,
    blackLen: 3,
    blackPos: 1,
  },
  // {
  //   label: 'Lobo Alves Palhares Costa Palhinha Gonçalves',
  //   position: 'Midfielder',
  //   value: 'Lobo Alves Palhares Costa Palhinha Gonçalves',
  //   id: 'ecp0v1dxqfjbgy3urnkz5d3o5',
  //   shirtNumber: '16',
  //   shortFirstName: 'João',
  //   shortLastName: 'Palhinha',
  //   posLen: 1,
  //   currentPos: 1,
  //   grayLen: 1,
  //   grayPos: 1,
  //   blackLen: 1,
  //   blackPos: 1,
  // },
  {
    label: 'Musiala',
    position: 'Forward',
    value: 'Musiala',
    id: 'bhsdzppop8jwjsxwftizot1t6',
    shirtNumber: '10',
    shortFirstName: 'Jamal',
    shortLastName: 'Musiala',
    arabicName: 'موسيالا',
    posLen: 4,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 2,
    blackPos: 1,
  },
  // {
  //   label: 'Müller',
  //   position: 'Forward',
  //   value: 'Müller',
  //   id: '4fq74wp7xzwm214veuxqpdz9x',
  //   shirtNumber: '25',
  //   shortFirstName: 'Thomas',
  //   shortLastName: 'Müller'
  // },
  {
    label: 'Neuer',
    position: 'Goalkeeper',
    value: 'Neuer',
    id: '64pzn3jdqo6y2izlpm8n3tvpx',
    shirtNumber: '1',
    shortFirstName: 'Manuel',
    shortLastName: 'Neuer',
    arabicName: 'نوير',
    posLen: 1,
    currentPos: 1,
    grayLen: 2,
    grayPos: 1,
    blackLen: 3,
    blackPos: 1,
  },
  {
    label: 'Olise',
    position: 'Midfielder',
    value: 'Olise',
    id: 'm2c4lckkcr7yilnqxrrsgh2i',
    shirtNumber: '17',
    shortFirstName: 'Michael',
    shortLastName: 'Olise',
    arabicName: 'أوليسي',
    posLen: 4,
    currentPos: 1,
    grayLen: 2,
    grayPos: 1,
    blackLen: 3,
    blackPos: 1,
  },
  {
    label: 'Pavlović',
    position: 'Midfielder',
    value: 'Pavlović',
    id: '9u0jnvttp25l5bp2pvx7pces',
    shirtNumber: '45',
    shortFirstName: 'Aleksandar',
    shortLastName: 'Pavlović',
    arabicName: 'بافلوفيتش',
    posLen: 3,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
  },
  // {
  //   label: 'Peretz',
  //   position: 'Goalkeeper',
  //   value: 'Peretz',
  //   id: '5y4i3tmhz8p24vfhccjzg5n8p',
  //   shirtNumber: '18',
  //   shortFirstName: 'Daniel',
  //   shortLastName: 'Peretz'
  // },
  // {
  //   label: 'Sané',
  //   position: 'Forward',
  //   value: 'Sané',
  //   id: '4603xrdk721lqhd1ejn62x5n9',
  //   shirtNumber: '10',
  //   shortFirstName: 'Leroy',
  //   shortLastName: 'Sané'
  // },
  // {
  //   label: 'Tel',
  //   position: 'Forward',
  //   value: 'Tel',
  //   id: 'cv1d56d42wujfuc4kt6bn53x0',
  //   shirtNumber: '39',
  //   shortFirstName: 'Mathys',
  //   shortLastName: 'Tel'
  // },
  {
    label: 'Ulreich',
    position: 'Goalkeeper',
    value: 'Ulreich',
    id: 'br2uswvdgoj7ndkx7mnbwgyd',
    shirtNumber: '26',
    shortFirstName: 'Sven',
    shortLastName: 'Ulreich',
    arabicName: 'أولرايش',
    grayLen: 1,
    grayPos: 1,
  },
  {
    label: 'Upamecano',
    position: 'Defender',
    value: 'Upamecano',
    id: 'x4qyxhfr2vi007sazoqe5vit',
    shirtNumber: '2',
    shortFirstName: 'Dayot',
    shortLastName: 'Upamecano',
    arabicName: 'أوباميكانو',
    posLen: 2,
    currentPos: 1,
    grayLen: 2,
    grayPos: 1,
    blackLen: 2,
    blackPos: 1,
  },
  {
    firstName: "Vincent",
    lastName: "Manuba",
    label: "Manuba",
    matchName: "Manuba",
    id: "2i8mia6uantvhtmpewgs1qz9w",
    shirtNumber: 41,
    shortFirstName: "Vincent",
    shortLastName: "Manuba",
    arabicName: 'مانوبا',
    position: "Attacker",
    posLen: 1,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
  },
  {
    firstName: "Josip",
    formationPlace: "3",
    lastName: "Stanišić",
    matchName: "J. Stanišić",
    id: "4skrm2y64va3y5jk70gz4ylpm",
    position: "Defender",
    positionSide: "Left",
    shirtNumber: 44,
    shortFirstName: "Josip",
    shortLastName: "Stanišić",
    label: "Stanišić",
    arabicName: 'ستانيشيتش',
    posLen: 2,
    currentPos: 1,
    grayLen: 3,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
  },
  {
    firstName: "Jonathan",
    formationPlace: "6",
    lastName: "Glao Tah",
    matchName: "J. Tah",
    id: "5ec2ede9uwbft3wby33mwowyd",
    position: "Defender",
    positionSide: "Left/Centre",
    shirtNumber: 4,
    shortFirstName: "Jonathan",
    shortLastName: "Tah",
    arabicName: 'تاه',
    label: "Tah",
    posLen: 2,
    currentPos: 1,
    grayLen: 2,
    grayPos: 1,
    blackLen: 2,
    blackPos: 1,
  },
  {
    firstName: "Tom",
    lastName: "Bischof",
    matchName: "T. Bischof",
    id: "6sj31v61vtwwxe5hhwkj80g7o",
    shirtNumber: 20,
    shortFirstName: "Tom",
    shortLastName: "Bischof",
    position: "Midfielder",
    label: "Bischof",
    arabicName: 'بيشوف',
    posLen: 2,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
  },
  {

    firstName: "Lennart",
    lastName: "Karl",
    matchName: "L. Karl",
    id: "b4x911h58r8i9b2vvsnydvfo4",
    shirtNumber: 42,
    shortFirstName: "Lennart",
    shortLastName: "Karl",
    position: "Midfielder",
    label: "Karl",
    arabicName: 'كارل',
    posLen: 3,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,

  },
  {
    firstName: "David Michael",
    knownName: "David Daiber",
    lastName: "Santos Daiber",
    matchName: "David Daiber",
    id: "qt1wbjej8amtydluzvfudhxw",
    shirtNumber: 47,
    shortFirstName: "David Michael",
    shortLastName: "Santos",
    arabicName: 'سانتوس دايبر',
    position: "Midfielder",
    label: "Santos",
    posLen: 1,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
  },
  {
    firstName: "Wisdom",
    lastName: "Mike",
    matchName: "Mike",
    id: "clrnb4f1yk8z6fbcwyv9vmkus", //clrnb4f1yk8z6fbcwyv9vmkus
    shirtNumber: 36,
    shortFirstName: "Wisdom",
    shortLastName: "Mike",
    position: "Forward",
    label: "Mike",
    arabicName: 'مايك',
    posLen: 1,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
  },
  {
    label: 'Urbig',
    position: 'Goalkeeper',
    value: 'Urbig',
    id: '91n9wzn3qq2789zq8vdmfrd62',
    shirtNumber: '40',
    shortFirstName: 'Jonas',
    shortLastName: 'Urbig',
    arabicName: 'أوربيج',
    posLen: 1,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
  },
  {
    firstName: "",
    lastName: "Bärtl",
    matchName: "Bärtl",
    id: "fcb_bartl_goalkeeper",
    shirtNumber: 35,
    shortFirstName: "",
    shortLastName: "Bärtl",
    position: "Goalkeeper",
    label: "Bärtl",
    arabicName: 'بارتل',
    posLen: 1,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
    hasId: false,
  },
  {
    firstName: "",
    lastName: "Pavlešić",
    matchName: "Pavlešić",
    id: "fcb_pavlesic_goalkeeper",
    shirtNumber: 37,
    shortFirstName: "",
    shortLastName: "Pavlešić",
    position: "Goalkeeper",
    label: "Pavlešić",
    arabicName: 'بافليسيتش',
    posLen: 1,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
    hasId: false,
  },
  {
    firstName: "",
    lastName: "Chávez",
    matchName: "Chávez",
    id: "fcb_chavez_forward",
    shirtNumber: 38,
    shortFirstName: "",
    shortLastName: "Chávez",
    position: "Forward",
    label: "Chávez",
    arabicName: 'تشافيز',
    posLen: 1,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
    hasId: false,
  },
  // {
  //   label: 'Buchmann',
  //   position: 'Forward',
  //   value: 'Buchmann',
  //   id: 'fcb_buchmann_forward',
  //   shirtNumber: '28',
  //   shortFirstName: 'Luca',
  //   shortLastName: 'Buchmann',
  //   posLen: 1,
  //   currentPos: 1,
  //   grayLen: 1,
  //   grayPos: 1,
  //   blackLen: 1,
  //   blackPos: 1,
  // },
  {
    firstName: "",
    lastName: "Dalpiaz",
    matchName: "Dalpiaz",
    id: "fcb_dalpiaz_forward",
    shirtNumber: 49,
    shortFirstName: "",
    shortLastName: "Dalpiaz",
    position: "Forward",
    label: "Dalpiaz",
    posLen: 1,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
    hasId: false,
  },

  {
    label: 'Ito',
    position: 'Forward',
    value: 'Ito',
    id: 'fcb_ito_forward',
    shirtNumber: '21',
    shortFirstName: 'Ito',
    shortLastName: 'Ito',
    arabicName: 'إيتو',
    posLen: 2,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
    hasId: false,
  },

  {
    label: 'Wanner',
    position: 'Forward',
    value: 'Wanner',
    id: 'fcb_wanner_forward',
    shirtNumber: '24',
    shortFirstName: 'Wanner',
    shortLastName: 'Wanner',
    arabicName: 'فانر',
    posLen: 1,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
    hasId: false,
  },

  {
    label: 'Kiala',
    position: 'Centre‑back',
    value: 'Kiala',
    id: 'fcb_Kiala_center_back',
    shirtNumber: '30',
    shortFirstName: 'Kiala',
    shortLastName: 'Kiala',
    arabicName: 'كيالا',
    posLen: 2,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
    hasId: false,
  },
  {
    label: 'Klanac',
    position: 'Goalkeeper',
    value: 'Klanac',
    id: 'fcb_klanac_goalkeeper',
    shirtNumber: '48',
    shortFirstName: 'Leon',
    shortLastName: 'Klanac',
    arabicName: 'كلاناك',
    posLen: 1,
    currentPos: 1,
    grayLen: 1,
    grayPos: 1,
    blackLen: 1,
    blackPos: 1,
    hasId: false,
  },
];

module.exports = {
  fcbLineupPlayers
};
