module.exports = {
  uuid: '0',
  template_name: 'bild_standings',
  name: 'Standings',
  data: {
    dynamic: {
      matchInfo: {
        id: '5rwmb91p8fs2zfjsf633fm3h0',
        coverageLevel: '15',
        date: '2023-10-28Z',
        time: '13:30:00Z',
        localDate: '2023-10-28',
        localTime: '15:30:00',
        week: '9',
        numberOfPeriods: 2,
        periodLength: 45,
        lastUpdated: '2024-03-30T13:43:48Z',
        description: 'Augsburg vs Wolfsburg',
        sport: {
          id: '289u5typ3vp4ifwh5thalohmq',
          name: 'Soccer'
        },
        ruleset: {
          id: '79plas4983031idr6vw83nuel',
          name: 'Men'
        },
        competition: {
          id: '6by3h89i2eykc341oz7lv1ddd',
          name: 'Bundesliga',
          knownName: 'German Bundesliga',
          competitionCode: 'BUN',
          competitionFormat: 'Domestic league',
          country: {
            id: '36min0qztu8eydwvpv8t1is0m',
            name: 'Germany'
          }
        },
        tournamentCalendar: {
          id: '9b9nvvpz477r8yrzmorx8w6qc',
          startDate: '2023-08-18Z',
          endDate: '2024-05-18Z',
          name: '2023/2024'
        },
        stage: {
          id: '9bygpthbfowvlhz0fijbs20b8',
          formatId: 'e2q01r9o9jwiq1fls93d1sslx',
          startDate: '2023-08-18Z',
          endDate: '2024-05-18Z',
          name: 'Regular Season'
        },
        contestant: [
          {
            id: 'ex3psl8e3ajeypwjy4xfltpx6',
            name: 'Augsburg',
            shortName: 'Augsburg',
            officialName: 'FC Augsburg',
            code: 'FCA',
            position: 'home',
            country: {
              id: '36min0qztu8eydwvpv8t1is0m',
              name: 'Germany'
            }
          },
          {
            id: 'a8l3w3n0j99qjlsxj3jnmgkz1',
            name: 'Wolfsburg',
            shortName: 'Wolfsburg',
            officialName: 'VfL Wolfsburg',
            code: 'WOB',
            position: 'away',
            country: {
              id: '36min0qztu8eydwvpv8t1is0m',
              name: 'Germany'
            }
          }
        ],
        venue: {
          id: '2hmegahk0ne8p900crfrh495o',
          neutral: 'no',
          longName: 'WWK Arena',
          shortName: 'WWK Arena'
        }
      },
      standing: [
        {
          type: 'total',
          ranking: [
            {
              rank: 1,
              rankStatus: 'UEFA Champions League',
              rankId: '1xsyqokuvcgxzkrp50fdv6efh',
              achievementStatus: 3,
              achievementType: 8,
              achievementStatus1: 2,
              achievementType1: 1,
              achievementStatus2: 2,
              achievementType2: 3,
              achievementStatus3: 3,
              achievementType3: 7,
              achievementStatus4: 2,
              achievementType4: 2,
              achievementStatus5: 2,
              achievementType5: 4,
              lastRank: 1,
              contestantId: '7ad69ngbpjuyzv96drf8d9sn2',
              contestantName: 'Bayer 04 Leverkusen',
              contestantShortName: 'Leverkusen',
              contestantClubName: 'Bayer Leverkusen',
              contestantCode: 'LEV',
              points: 76,
              matchesPlayed: 28,
              matchesWon: 24,
              matchesLost: 0,
              matchesDrawn: 4,
              goalsFor: 69,
              goalsAgainst: 19,
              goaldifference: '+50',
              lastSix: 'WWWWWW'
            },
            {
              rank: 2,
              rankStatus: 'UEFA Champions League',
              rankId: '1xsyqokuvcgxzkrp50fdv6efh',
              achievementStatus: 2,
              achievementType: 3,
              achievementStatus1: 3,
              achievementType1: 7,
              achievementStatus2: 2,
              achievementType2: 2,
              achievementStatus3: 2,
              achievementType3: 4,
              achievementStatus4: 3,
              achievementType4: 8,
              achievementStatus5: 2,
              achievementType5: 1,
              lastRank: 2,
              contestantId: 'apoawtpvac4zqlancmvw4nk4o',
              contestantName: 'FC Bayern München',
              contestantShortName: 'Bayern München',
              contestantClubName: 'Bayern München',
              contestantCode: 'FCB',
              points: 60,
              matchesPlayed: 28,
              matchesWon: 19,
              matchesLost: 6,
              matchesDrawn: 3,
              goalsFor: 80,
              goalsAgainst: 36,
              goaldifference: '+44',
              lastSix: 'LLWWDW'
            },
            {
              rank: 3,
              rankStatus: 'UEFA Champions League',
              rankId: '1xsyqokuvcgxzkrp50fdv6efh',
              achievementStatus: 2,
              achievementType: 2,
              achievementStatus1: 2,
              achievementType1: 4,
              achievementStatus2: 3,
              achievementType2: 8,
              achievementStatus3: 2,
              achievementType3: 1,
              achievementStatus4: 2,
              achievementType4: 3,
              achievementStatus5: 3,
              achievementType5: 7,
              lastRank: 3,
              contestantId: '3dwlvz6cl4lcavvrg0y2dycrt',
              contestantName: 'VfB Stuttgart 1893',
              contestantShortName: 'Stuttgart',
              contestantClubName: 'Stuttgart',
              contestantCode: 'VFB',
              points: 60,
              matchesPlayed: 28,
              matchesWon: 19,
              matchesLost: 6,
              matchesDrawn: 3,
              goalsFor: 64,
              goalsAgainst: 34,
              goaldifference: '+30',
              lastSix: 'WDWWWD'
            },
            {
              rank: 4,
              rankStatus: 'UEFA Champions League',
              rankId: '1xsyqokuvcgxzkrp50fdv6efh',
              achievementStatus: 2,
              achievementType: 3,
              achievementStatus1: 3,
              achievementType1: 7,
              achievementStatus2: 2,
              achievementType2: 2,
              achievementStatus3: 2,
              achievementType3: 4,
              achievementStatus4: 3,
              achievementType4: 8,
              achievementStatus5: 3,
              achievementType5: 1,
              lastRank: 5,
              contestantId: '9gefq4dz9b2hl8rqrxwrlrzmp',
              contestantName: 'RasenBallsport Leipzig',
              contestantShortName: 'Leipzig',
              contestantClubName: 'RB Leipzig',
              contestantCode: 'RBL',
              points: 53,
              matchesPlayed: 28,
              matchesWon: 16,
              matchesLost: 7,
              matchesDrawn: 5,
              goalsFor: 64,
              goalsAgainst: 33,
              goaldifference: '+31',
              lastSix: 'WDWWWL'
            },
            {
              rank: 5,
              rankStatus: 'UEFA Europa League',
              rankId: '1xt2mn30d08xoq74o01x3o77x',
              achievementStatus: 3,
              achievementType: 7,
              achievementStatus1: 2,
              achievementType1: 2,
              achievementStatus2: 2,
              achievementType2: 4,
              achievementStatus3: 3,
              achievementType3: 8,
              achievementStatus4: 2,
              achievementType4: 1,
              achievementStatus5: 2,
              achievementType5: 3,
              lastRank: 4,
              contestantId: 'dt4pinj0vw0t0cvz7za6mhmzy',
              contestantName: 'BV Borussia 09 Dortmund',
              contestantShortName: 'Dortmund',
              contestantClubName: 'Borussia Dortmund',
              contestantCode: 'BVB',
              points: 53,
              matchesPlayed: 28,
              matchesWon: 15,
              matchesLost: 5,
              matchesDrawn: 8,
              goalsFor: 55,
              goalsAgainst: 33,
              goaldifference: '+22',
              lastSix: 'LWWWWL'
            },
            {
              rank: 6,
              rankStatus: 'UEFA Conference League Qualifiers',
              rankId: '64dc9j63xdkc1b7g8t2k2vd3o',
              achievementStatus: 3,
              achievementType: 1,
              achievementStatus1: 2,
              achievementType1: 3,
              achievementStatus2: 3,
              achievementType2: 7,
              achievementStatus3: 2,
              achievementType3: 2,
              achievementStatus4: 2,
              achievementType4: 4,
              achievementStatus5: 2,
              achievementType5: 8,
              lastRank: 6,
              contestantId: 'c5hderjlkcoaze51e5wgvptk',
              contestantName: 'Eintracht Frankfurt',
              contestantShortName: 'Frankfurt',
              contestantClubName: 'Eintracht Frankfurt',
              contestantCode: 'SGE',
              points: 42,
              matchesPlayed: 28,
              matchesWon: 10,
              matchesLost: 6,
              matchesDrawn: 12,
              goalsFor: 43,
              goalsAgainst: 36,
              goaldifference: '+7',
              lastSix: 'DDLWWD'
            },
            {
              rank: 7,
              achievementStatus: 2,
              achievementType: 8,
              achievementStatus1: 3,
              achievementType1: 1,
              achievementStatus2: 2,
              achievementType2: 3,
              achievementStatus3: 2,
              achievementType3: 7,
              achievementStatus4: 2,
              achievementType4: 2,
              achievementStatus5: 2,
              achievementType5: 4,
              lastRank: 7,
              contestantId: 'ex3psl8e3ajeypwjy4xfltpx6',
              contestantName: 'FC Augsburg',
              contestantShortName: 'Augsburg',
              contestantClubName: 'Augsburg',
              contestantCode: 'FCA',
              points: 36,
              matchesPlayed: 28,
              matchesWon: 9,
              matchesLost: 10,
              matchesDrawn: 9,
              goalsFor: 45,
              goalsAgainst: 46,
              goaldifference: '-1',
              lastSix: 'LDWWWW'
            },
            {
              rank: 8,
              achievementStatus: 2,
              achievementType: 7,
              achievementStatus1: 2,
              achievementType1: 2,
              achievementStatus2: 2,
              achievementType2: 4,
              achievementStatus3: 2,
              achievementType3: 8,
              achievementStatus4: 3,
              achievementType4: 1,
              achievementStatus5: 2,
              achievementType5: 3,
              lastRank: 9,
              contestantId: '4l9mrqzmajz5crzlz50mtbt6x',
              contestantName: 'TSG 1899 Hoffenheim',
              contestantShortName: 'Hoffenheim',
              contestantClubName: 'Hoffenheim',
              contestantCode: 'TSG',
              points: 36,
              matchesPlayed: 28,
              matchesWon: 10,
              matchesLost: 12,
              matchesDrawn: 6,
              goalsFor: 48,
              goalsAgainst: 53,
              goaldifference: '-5',
              lastSix: 'WLLLWW'
            },
            {
              rank: 9,
              achievementStatus: 2,
              achievementType: 4,
              achievementStatus1: 2,
              achievementType1: 8,
              achievementStatus2: 3,
              achievementType2: 1,
              achievementStatus3: 2,
              achievementType3: 3,
              achievementStatus4: 2,
              achievementType4: 7,
              achievementStatus5: 2,
              achievementType5: 2,
              lastRank: 8,
              contestantId: '6k5zscdm9ufw0tguvzyjlp5hq',
              contestantName: 'SC Freiburg',
              contestantShortName: 'Freiburg',
              contestantClubName: 'Freiburg',
              contestantCode: 'SCF',
              points: 36,
              matchesPlayed: 28,
              matchesWon: 10,
              matchesLost: 12,
              matchesDrawn: 6,
              goalsFor: 40,
              goalsAgainst: 52,
              goaldifference: '-12',
              lastSix: 'LWLWDL'
            },
            {
              rank: 10,
              achievementStatus: 2,
              achievementType: 4,
              achievementStatus1: 2,
              achievementType1: 8,
              achievementStatus2: 3,
              achievementType2: 1,
              achievementStatus3: 2,
              achievementType3: 3,
              achievementStatus4: 2,
              achievementType4: 7,
              achievementStatus5: 3,
              achievementType5: 2,
              lastRank: 11,
              contestantId: '3xcg7xikgrn2x8oa65sopb2is',
              contestantName: '1. FC Heidenheim 1846',
              contestantShortName: 'Heidenheim',
              contestantClubName: 'Heidenheim',
              contestantCode: 'HDH',
              points: 33,
              matchesPlayed: 28,
              matchesWon: 8,
              matchesLost: 11,
              matchesDrawn: 9,
              goalsFor: 41,
              goalsAgainst: 49,
              goaldifference: '-8',
              lastSix: 'WDDLLD'
            },
            {
              rank: 11,
              achievementStatus: 3,
              achievementType: 3,
              achievementStatus1: 2,
              achievementType1: 7,
              achievementStatus2: 3,
              achievementType2: 2,
              achievementStatus3: 2,
              achievementType3: 4,
              achievementStatus4: 2,
              achievementType4: 8,
              achievementStatus5: 3,
              achievementType5: 1,
              lastRank: 13,
              contestantId: 'go76xxm0xyfgqt1h6tcrtimm',
              contestantName: 'Borussia VfL Mönchengladbach',
              contestantShortName: "M'gladbach",
              contestantClubName: "Borussia M'gladbach",
              contestantCode: 'BMG',
              points: 31,
              matchesPlayed: 28,
              matchesWon: 7,
              matchesLost: 11,
              matchesDrawn: 10,
              goalsFor: 49,
              goalsAgainst: 54,
              goaldifference: '-5',
              lastSix: 'WLDDDW'
            },
            {
              rank: 12,
              achievementStatus: 2,
              achievementType: 4,
              achievementStatus1: 2,
              achievementType1: 8,
              achievementStatus2: 3,
              achievementType2: 1,
              achievementStatus3: 2,
              achievementType3: 3,
              achievementStatus4: 2,
              achievementType4: 7,
              achievementStatus5: 3,
              achievementType5: 2,
              lastRank: 10,
              contestantId: 'cu0eztmjcsbydyp53aleznorw',
              contestantName: 'SV Werder Bremen',
              contestantShortName: 'Bremen',
              contestantClubName: 'Werder Bremen',
              contestantCode: 'SVW',
              points: 31,
              matchesPlayed: 28,
              matchesWon: 8,
              matchesLost: 13,
              matchesDrawn: 7,
              goalsFor: 36,
              goalsAgainst: 44,
              goaldifference: '-8',
              lastSix: 'DLLLLD'
            },
            {
              rank: 13,
              achievementStatus: 2,
              achievementType: 4,
              achievementStatus1: 2,
              achievementType1: 8,
              achievementStatus2: 3,
              achievementType2: 1,
              achievementStatus3: 2,
              achievementType3: 3,
              achievementStatus4: 2,
              achievementType4: 7,
              achievementStatus5: 3,
              achievementType5: 2,
              lastRank: 12,
              contestantId: 'a8d2gb2nag8fy0itbuxmcibh2',
              contestantName: '1. FC Union Berlin',
              contestantShortName: 'Union Berlin',
              contestantClubName: 'Union Berlin',
              contestantCode: 'FCU',
              points: 29,
              matchesPlayed: 28,
              matchesWon: 8,
              matchesLost: 15,
              matchesDrawn: 5,
              goalsFor: 25,
              goalsAgainst: 43,
              goaldifference: '-18',
              lastSix: 'LDWLLD'
            },
            {
              rank: 14,
              achievementStatus: 2,
              achievementType: 7,
              achievementStatus1: 3,
              achievementType1: 2,
              achievementStatus2: 2,
              achievementType2: 4,
              achievementStatus3: 2,
              achievementType3: 8,
              achievementStatus4: 3,
              achievementType4: 1,
              achievementStatus5: 3,
              achievementType5: 3,
              lastRank: 14,
              contestantId: 'a8l3w3n0j99qjlsxj3jnmgkz1',
              contestantName: 'VfL Wolfsburg',
              contestantShortName: 'Wolfsburg',
              contestantClubName: 'Wolfsburg',
              contestantCode: 'WOB',
              points: 28,
              matchesPlayed: 28,
              matchesWon: 7,
              matchesLost: 14,
              matchesDrawn: 7,
              goalsFor: 34,
              goalsAgainst: 47,
              goaldifference: '-13',
              lastSix: 'LWLLLD'
            },
            {
              rank: 15,
              achievementStatus: 2,
              achievementType: 8,
              achievementStatus1: 3,
              achievementType1: 1,
              achievementStatus2: 3,
              achievementType2: 3,
              achievementStatus3: 2,
              achievementType3: 7,
              achievementStatus4: 3,
              achievementType4: 2,
              achievementStatus5: 2,
              achievementType5: 4,
              lastRank: 15,
              contestantId: 'eq1oq6y61xnzq88zu0cnw131z',
              contestantName: 'VfL Bochum 1848',
              contestantShortName: 'Bochum',
              contestantClubName: 'Bochum',
              contestantCode: 'BOC',
              points: 26,
              matchesPlayed: 28,
              matchesWon: 5,
              matchesLost: 12,
              matchesDrawn: 11,
              goalsFor: 33,
              goalsAgainst: 58,
              goaldifference: '-25',
              lastSix: 'LDLLLL'
            },
            {
              rank: 16,
              rankStatus: 'Relegation Play-off',
              rankId: '1xsyan79mcovxauuj4ge3iwst',
              achievementStatus: 3,
              achievementType: 2,
              achievementStatus1: 2,
              achievementType1: 4,
              achievementStatus2: 2,
              achievementType2: 8,
              achievementStatus3: 3,
              achievementType3: 1,
              achievementStatus4: 3,
              achievementType4: 3,
              achievementStatus5: 2,
              achievementType5: 7,
              lastRank: 16,
              contestantId: '1c7qokc1j5z50cjj4tcu32haa',
              contestantName: '1. FSV Mainz 05',
              contestantShortName: 'Mainz 05',
              contestantClubName: 'Mainz 05',
              contestantCode: 'M05',
              points: 23,
              matchesPlayed: 28,
              matchesWon: 4,
              matchesLost: 13,
              matchesDrawn: 11,
              goalsFor: 26,
              goalsAgainst: 46,
              goaldifference: '-20',
              lastSix: 'WDWLDL'
            },
            {
              rank: 17,
              rankStatus: 'Relegation',
              rankId: '1xsy07o6mnddbc0p9a02jhojx',
              achievementStatus: 3,
              achievementType: 2,
              achievementStatus1: 3,
              achievementType1: 4,
              achievementStatus2: 2,
              achievementType2: 8,
              achievementStatus3: 3,
              achievementType3: 1,
              achievementStatus4: 3,
              achievementType4: 3,
              achievementStatus5: 2,
              achievementType5: 7,
              lastRank: 17,
              contestantId: '8q1ul09cygzswb7tb456bmifv',
              contestantName: '1. FC Köln',
              contestantShortName: 'Köln',
              contestantClubName: 'Köln',
              contestantCode: 'KOE',
              points: 22,
              matchesPlayed: 28,
              matchesWon: 4,
              matchesLost: 14,
              matchesDrawn: 10,
              goalsFor: 23,
              goalsAgainst: 49,
              goaldifference: '-26',
              lastSix: 'WDLDLD'
            },
            {
              rank: 18,
              rankStatus: 'Relegation',
              rankId: '1xsy07o6mnddbc0p9a02jhojx',
              achievementStatus: 3,
              achievementType: 3,
              achievementStatus1: 2,
              achievementType1: 7,
              achievementStatus2: 3,
              achievementType2: 2,
              achievementStatus3: 3,
              achievementType3: 4,
              achievementStatus4: 2,
              achievementType4: 8,
              achievementStatus5: 3,
              achievementType5: 1,
              lastRank: 18,
              contestantId: '1y7e48j8swyafegsucvewse5a',
              contestantName: 'SV Darmstadt 1898',
              contestantShortName: 'Darmstadt 98',
              contestantClubName: 'Darmstadt 98',
              contestantCode: 'D98',
              points: 14,
              matchesPlayed: 28,
              matchesWon: 2,
              matchesLost: 18,
              matchesDrawn: 8,
              goalsFor: 28,
              goalsAgainst: 71,
              goaldifference: '-43',
              lastSix: 'LDLLLD'
            }
          ]
        }
      ]
    },
    fields: [],
    options: [
      {
        id: 'name',
        label: 'Name',
        type: 'text',
        value: 'Standings'
      },
      {
        id: 'color1',
        label: 'Color 1',
        type: 'color',
        value: '#00FDFF'
      },
      {
        id: 'color2',
        label: 'Color 2',
        type: 'color',
        value: '#919191'
      },
      {
        id: 'videoduration',
        label: 'Video duration',
        type: 'text',
        value: '15'
      }
    ],
    videos: {
      '1920x1080': {
        date: null,
        file: null
      }
    }
  },
  season: '2022',
  event: {
    selectedTeamId: 'ea68amhsn28ijs7bzjuzeqrz6',
    competitionId: '2a8elwzsufmguwymxbshcx756',
    competitionName: '2022 Qatar',
    type: 'match',
    homeTeamId: 'ea68amhsn28ijs7bzjuzeqrz6',
    awayTeamId: '2j2402oabiovxw24cnjk9m369',
    side: 'home',
    eventId: 'ak5kkxvpxf1url15gci42ly7e',
    dateObj: '202130203023',
    date: '20.11.2022',
    start_date: null,
    time: '17:00'
  }
};
